### ISSUE TITLE
Creación Método Sueldo

### ISSUE THREAD

**Issue by mariaapl20** [mariaapl20/TrabajoGrupoEEDD#10]
En dicho método se va a guardar el sueldo del trabajador (tipo int).

**Comment by Josanloca** [comment]
Ya esta terminada terminado este metodo aqui la foto correspondiente.

![unknown](https://user-images.githubusercontent.com/58845435/74464624-2882ab80-4e94-11ea-8a19-7e4eb2109917.png)
