### ISSUE TITLE
Creación Método Antigüedad

### ISSUE THREAD

**Issue by Fernandorp7** [mariaapl20/TrabajoGrupoEEDD#11]
En dicho método se va a guardar la antigüedad del trabajador (Tipo String)

**Comment by jvegadelahera** [comment]
Esta tarea ya esta realizada y finalizada. 

![image](https://user-images.githubusercontent.com/58937165/74560524-086fec80-4f67-11ea-9b8c-ccea6e85854e.png)
 
Aquí refiero la foto en la se muestra echa la tarea
