### ISSUE TITLE
Creación Método Número Alumno

### ISSUE THREAD

**Issue by mariaapl20** [mariaapl20/TrabajoGrupoEEDD#12]
En dicho método se va a guardar el número de alumnos al que un profesor imparte clases (tipo int).

**Comment by Josanloca** [comment]
Ya esta creado los metodos de numero alumnos y aqui le dejo una captura correspondiente



![unknown](https://user-images.githubusercontent.com/58845435/74464040-1ce2b500-4e93-11ea-897c-9f94ea29bd60.png)

**Comment by Josanloca** [comment]
Ya estaria listo el metodo de numero alumnos aqui le dejo una foto correspondiente y cierro esta tarea.

![imagen](https://user-images.githubusercontent.com/58845435/74464158-54e9f800-4e93-11ea-8386-3be729e6f690.png)
