### ISSUE TITLE
Creación Método Funcionario

### ISSUE THREAD

**Issue by Fernandorp7** [mariaapl20/TrabajoGrupoEEDD#13]
En este método se va a guardar si el profesor es un funcionario o no lo es (Tipo Boolean)

**Comment by jvegadelahera** [comment]
La creación del método funcionario ha terminado. aquí remito foto del método.

![image](https://user-images.githubusercontent.com/58937165/74560730-75838200-4f67-11ea-971c-3284d6b2e886.png)
