### ISSUE TITLE
Creación Método Apellidos

### ISSUE THREAD

**Issue by Fernandorp7** [mariaapl20/TrabajoGrupoEEDD#6]
En dicho método se va a guardar los apellidos de las personas  (tipo String).

**Comment by mariaapl20** [comment]
Ya esta terminado el método de esta tarea. La foto correspondiente:
![Captura](https://user-images.githubusercontent.com/58971815/74465342-81067880-4e95-11ea-8b3e-a1a90d2cd7ee.PNG)

**Comment by Fernandorp7** [comment]
El método apellidos ha sido cerrado correctamente.

![image](https://user-images.githubusercontent.com/58937175/74561257-87b1f000-4f68-11ea-9c82-ed7ec6f79742.png)
