### ISSUE TITLE
Creación Método Universidad

### ISSUE THREAD

**Issue by Fernandorp7** [mariaapl20/TrabajoGrupoEEDD#9]
En dicho método se va a guardar la universidad a la que este asociado el profesor (Tipo String)

**Comment by Josanloca** [comment]
Ya esta hecho el push correspondiente aqui tienes una captura que lo demuestre
![unknown](https://user-images.githubusercontent.com/58845435/74473878-aa7ad080-4ea4-11ea-8ea3-7258405b77ac.png)

**Comment by Josanloca** [comment]
Testeo de prueba del cerrado automatico
